import { Horse, User, Booking } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    role: 'owner',
    phone: '555-0101',
    location: 'Manhasset, NY',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Emma Williams',
    email: 'emma@example.com',
    role: 'rider',
    phone: '555-0102',
    location: 'Great Neck, NY',
    verifiedBy: '3',
    createdAt: new Date('2024-02-20'),
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael@example.com',
    role: 'trainer',
    phone: '555-0103',
    location: 'Old Westbury, NY',
    createdAt: new Date('2023-11-10'),
  },
];

export const mockHorses: Horse[] = [
  {
    id: '1',
    name: 'Starlight Dream',
    breed: 'Warmblood',
    age: 8,
    height: 16.2,
    color: 'Bay',
    gender: 'gelding',
    discipline: ['hunter', 'jumper'],
    skillLevelRequired: 'intermediate',
    leaseTypes: ['half', 'full'],
    onsiteOnly: false,
    location: 'Manhasset, NY',
    coordinates: { lat: 40.7982, lng: -73.6993 },
    price: {
      full: 2500,
      half: 1500,
    },
    description: 'Beautiful bay gelding with an excellent temperament. Perfect for a junior or adult amateur looking to compete in the 3\' hunter/jumper divisions. Very safe and forgiving, with clean flying changes and an auto-change. Has extensive show experience and is ready to take you into the ring.',
    features: [
      'Auto-change',
      'Loads/clips/ties',
      'No vices',
      'Current on all vaccines',
      'Regular farrier/dental care',
      'Easy keeper',
    ],
    images: [
      'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800',
      'https://images.unsplash.com/photo-1534346095187-8f03d889f96b?w=800',
    ],
    videoUrl: 'https://example.com/video1',
    ownerId: '1',
    ownerName: 'Sarah Johnson',
    showRecord: 'Multiple championships in 3\' Junior Hunter division',
    vetCheckDate: new Date('2024-11-01'),
    isVerified: true,
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    createdAt: new Date('2024-12-01'),
  },
  {
    id: '2',
    name: 'Midnight Magic',
    breed: 'Thoroughbred',
    age: 10,
    height: 16.0,
    color: 'Black',
    gender: 'mare',
    discipline: ['dressage', 'eventing'],
    skillLevelRequired: 'advanced',
    leaseTypes: ['half', 'quarter'],
    onsiteOnly: true,
    location: 'Roslyn, NY',
    coordinates: { lat: 40.7998, lng: -73.6510 },
    price: {
      half: 1800,
      quarter: 1000,
    },
    description: 'Stunning black Thoroughbred mare with incredible movement. Schooling 2nd level dressage with clean flying changes and lateral work. Has evented through Training level. Looking for an experienced rider who wants to continue her education.',
    features: [
      'Elegant mover',
      'Bold cross-country',
      'Loves to work',
      'Good for farrier/vet',
      'Trailers well',
    ],
    images: [
      'https://images.unsplash.com/photo-1598978546488-db7f90fcbd87?w=800',
      'https://images.unsplash.com/photo-1551884831-bbf3cdc6469e?w=800',
    ],
    ownerId: '1',
    ownerName: 'Sarah Johnson',
    showRecord: 'USDF Bronze Medal scores, Training Level Event completions',
    vetCheckDate: new Date('2024-10-15'),
    isVerified: true,
    availableDays: ['Tuesday', 'Thursday', 'Saturday'],
    createdAt: new Date('2024-11-15'),
  },
  {
    id: '3',
    name: 'Golden Boy',
    breed: 'Quarter Horse',
    age: 12,
    height: 15.2,
    color: 'Palomino',
    gender: 'gelding',
    discipline: ['western', 'hunter'],
    skillLevelRequired: 'beginner',
    leaseTypes: ['half', 'quarter'],
    onsiteOnly: false,
    location: 'Port Washington, NY',
    coordinates: { lat: 40.8257, lng: -73.6982 },
    price: {
      half: 1200,
      quarter: 700,
    },
    description: 'The perfect confidence builder! This kind, patient gelding is ideal for a beginner or nervous rider. Has experience in both western pleasure and English hunter divisions. Absolutely bombproof and safe for all ages.',
    features: [
      'Beginner safe',
      'Kid friendly',
      'No spook',
      'Push-button changes',
      'Great ground manners',
      'Easy to catch',
    ],
    images: [
      'https://images.unsplash.com/photo-1589419351-e06ed6ef4d90?w=800',
      'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800',
    ],
    ownerId: '1',
    ownerName: 'Sarah Johnson',
    showRecord: 'Multiple ribbons in local shows',
    vetCheckDate: new Date('2024-12-01'),
    isVerified: true,
    availableDays: ['Monday', 'Tuesday', 'Friday', 'Saturday'],
    createdAt: new Date('2024-10-01'),
  },
  {
    id: '4',
    name: 'Cavalier',
    breed: 'Dutch Warmblood',
    age: 7,
    height: 17.0,
    color: 'Chestnut',
    gender: 'gelding',
    discipline: ['jumper', 'equitation'],
    skillLevelRequired: 'advanced',
    leaseTypes: ['full'],
    onsiteOnly: false,
    location: 'Old Westbury, NY',
    coordinates: { lat: 40.7857, lng: -73.5993 },
    price: {
      full: 3500,
    },
    description: 'Talented jumper with scope for 3\'6" and above. Has competed successfully in the 1.20m division. Excellent equitation horse with smooth gaits and a beautiful jump. Looking for a serious competitor to take him to the next level.',
    features: [
      'Scopey jumper',
      'Big step',
      'Brave to the jumps',
      'Show experience',
      'Careful',
      'Professional training',
    ],
    images: [
      'https://images.unsplash.com/photo-1598978546488-db7f90fcbd87?w=800',
      'https://images.unsplash.com/photo-1533092810136-f2f8e9c35825?w=800',
    ],
    ownerId: '1',
    ownerName: 'Sarah Johnson',
    showRecord: 'Multiple wins in 1.20m Jumpers',
    vetCheckDate: new Date('2024-11-20'),
    isVerified: true,
    availableDays: ['Monday', 'Wednesday', 'Thursday', 'Friday'],
    createdAt: new Date('2024-09-01'),
  },
  {
    id: '5',
    name: 'Bella Luna',
    breed: 'Connemara Cross',
    age: 9,
    height: 14.2,
    color: 'Grey',
    gender: 'mare',
    discipline: ['hunter', 'equitation'],
    skillLevelRequired: 'beginner',
    leaseTypes: ['half', 'quarter'],
    onsiteOnly: true,
    location: 'Great Neck, NY',
    coordinates: { lat: 40.8007, lng: -73.7282 },
    price: {
      half: 1000,
      quarter: 600,
    },
    description: 'Sweet pony perfect for a young rider transitioning from lessons. Excellent eq pony with a smooth canter and simple changes. Has successfully shown in the short stirrup and children\'s pony divisions. Patient and forgiving.',
    features: [
      'Pony safe',
      'Show experience',
      'Smooth gaits',
      'No vices',
      'Easy keeper',
      'Great for grooming',
    ],
    images: [
      'https://images.unsplash.com/photo-1585287176634-f8da7d2e17fc?w=800',
      'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800',
    ],
    ownerId: '1',
    ownerName: 'Sarah Johnson',
    vetCheckDate: new Date('2024-11-10'),
    isVerified: true,
    availableDays: ['Monday', 'Wednesday', 'Saturday'],
    createdAt: new Date('2024-11-01'),
  },
];

export const mockBookings: Booking[] = [
  {
    id: '1',
    horseId: '1',
    riderId: '2',
    trainerId: '3',
    date: new Date('2025-01-20'),
    status: 'approved',
    notes: 'Looking forward to trying this horse for my daughter',
    trialRideFee: 75,
    createdAt: new Date('2025-01-10'),
  },
];
